question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Television",
        "question": "In 'Star Trek', Klingons are aliens.",
        "correct_answer": "True",
        "incorrect_answers": ["False"]
    },
    {
        "type": "boolean", "difficulty": "medium", "category": "Vehicles",
        "question": "Ferrari has never made a V10 engine for any of its cars.",
        "correct_answer": "False", "incorrect_answers": ["True"]
    },
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as 'The Shape'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Politics",
     "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Sports",
     "question": "There are a total of 20 races in Formula One 2016 season.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Tokyo is the capital of Japan.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "In the game 'Until Dawn' Emily is the only playable character who can be killed by another playable character directly.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.' is a grammatically correct sentence.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Cartoon & Animations",
     "question": "Nutcracker Suite was one of the musical pieces featured in Disney's 1940's film Fantasia.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The ultimate phrase used by Pharah from Overwatch is: 'Justice rains from above!'",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Hidden in the files for 'Mario Kart Arcade GP' is a picture of the Beslan school hostage crisis.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Gordon Freeman, the protagonist of 'Half-Life', is said to have once had a ponytail.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "AMC's 'The Walking Dead', Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Bulls are attracted to the color red.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "General Knowledge",
     "question": "This is the correct spelling of 'Supercalifragilisticexpialidocious'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "In 'Star Trek', Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "In 'Call Of Duty: World At War', the first appearance of the 'PPSH-41' in 'Zombies' was in the map 'Der Riese'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Entertainment: Japanese Anime & Manga",
     "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The sum of all the numbers on a roulette wheel is 666.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Mythology",
     "question": "A wyvern is the same as a dragon.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium",
                                      "category": "Entertainment: Video Games",
                                      "question": "In 'League of Legends', there exists four different types of Dragon.",
                                      "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "For his performance at ComplexCon 2016 in Long Beach, California, Skrillex revived his 'Mothership' set piece for one night only.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the video game 'Splatoon', the playable characters were originally going to be rabbits instead of squids.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The names of Tom Nook's cousins in the Animal Crossing franchise are named 'Timmy' and 'Jimmy'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Dave Grohl recorded the Foo Fighters' debut, 'Foo Fighters,' by himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Art",
     "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Television",
     "question": "The Klingon home planet is Qo'noS.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "The Great Wall of China is visible from the moon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The bikini is named after the 'Bikini Atoll', an island where the United States conducted tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "The United States was a member of the League of Nations.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "During Wimbledon, spectators in the grounds can buy the tennis balls that have been used in matches.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Politics",
     "question": "Helen Clark was the 37th Prime Minister of Australia.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Metallica collaborated with Rowan Atkinson's Mr Bean on a 1992 comic relief single.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "In World War ll, Great Britian used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy\/D-day landing.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Pluto is a planet.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Politics",
     "question": "There was a satirical candidate named 'Deez Nuts' running in the 2016 US presidential elections.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "The word 'Inception' came from the 2010 blockbuster hit 'Inception'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Science: Mathematics",
     "question": "The binary number '101001101' is equivalent to the Decimal number '334'",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Television",
     "question": "Bob Ross was a US Air Force pilot.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "Franz Joseph I was the last emperor of Austria.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "In the game 'Melty Blood Actress Again Current Code', you can enter Blood Heat mode in Half Moon style.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Donkey Kong was originally set to be a Popeye arcade game.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "The retail disc of Tony Hawk's Pro Skater 5 only comes with the tutorial.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "Sean Connery wasn't in 'Indiana Jones and the Kingdom of the Crystal Skull' because he found retirement too enjoyable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Japanese Anime & Manga",
     "question": "In the 'Kagerou Daze' series, Shintaro Kisaragi is prominently shown with the color red.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science & Nature",
     "question": "An Astronomical Unit is the distance between Earth and the Moon.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Dave Grohl recorded the Foo Fighters' debut, 'Foo Fighters,' by himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Japanese Anime & Manga",
     "question": "In 'To Love-Ru: Darkness', Yami reveals her real name is Eve.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
     "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
     "question": "A 'Millinillion' is a real number.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Geography",
     "question": "Japan has left-hand side traffic.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004's 'The Aviator'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Television",
     "question": "The Klingon home planet is Qo'noS.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Video streaming website YouTube was purchased in it's entirety by Facebook for US$1.65 billion in stock.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "The bikini is named after the 'Bikini Atoll', an island where the United States conducted tests on atomic bombs.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In 'Super Mario 3D World', the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science & Nature",
     "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "The Hundred Years' War was fought for more than a hundred years.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "Oxford University is older than the Aztec Empire. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the 'S.T.A.L.K.E.R.' series, the Freedom faction wishes to destroy the supernatural area known as  'the Zone'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In career mode of 'Need for Speed: Underground 2', the first car the player can drive is the BMW M3 GTR.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Politics",
     "question": "Joko Widodo has appeared in the cover of a TIME magazine.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Music",
     "question": "The singer Billie Holiday was also known as 'Lady Day'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
     "question": "111,111,111 x 111,111,111 = 12,345,678,987,654,321", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "A pasodoble is a type of Italian pasta sauce.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Japanese Anime & Manga",
     "question": "Throughout the entirety of 'Dragon Ball Z', Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Tony Hawk's Pro Skater was released in 1999.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime & Manga",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "hard", "category": "Science: Mathematics",
     "question": "The binary number '101001101' is equivalent to the Decimal number '334'",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
     "question": "Ferrari has never made a V10 engine for any of its cars.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Michael Jackson wrote The Simpsons song 'Do the Bartman'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Sports",
     "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Coca-Cola's original colour was green.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Art",
     "question": "Pablo Picasso is one of the founding fathers of 'Cubism.'",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "Peter Molyneux was the founder of Bullfrog Productions.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "The main character in the 'Half-Life' franchise is named Morgan Freeman.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
     "question": "Dihydrogen Monoxide is a dangerous chemical.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Ashley Frangipane performs under the stage name Halsey.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "hard", "category": "Geography",
     "question": "Only one country in the world starts with the letter Q.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "The cover of The Beatles album 'Abbey Road' featured a Volkswagen Beetle in the background.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
     "question": "Rapper Snoop Dogg's real name is 'Cordozar Calvin Broadus, Jr.'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
